connect to imdb;

set current schema imdb;

ALTER TABLE title 
	ADD CONSTRAINT "title_kind_type" FOREIGN KEY
		(kind_id)
	REFERENCES kind_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE aka_title 
	ADD CONSTRAINT "aka_title_kind_type" FOREIGN KEY
		(kind_id)
	REFERENCES kind_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE aka_title 
	ADD CONSTRAINT "aka_title_title" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_link 
	ADD CONSTRAINT "movie_link_title1" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_link 
	ADD CONSTRAINT "movie_link_title2" FOREIGN KEY
		(linked_movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_link 
	ADD CONSTRAINT "movie_link_link_type" FOREIGN KEY
		(link_type_id)
	REFERENCES link_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_keyword 
	ADD CONSTRAINT "movie_keyword_title" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_keyword 
	ADD CONSTRAINT "movie_keyword_keyword" FOREIGN KEY
		(keyword_id)
	REFERENCES keyword
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_info 
	ADD CONSTRAINT "movie_info_title" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_info 
	ADD CONSTRAINT "movie_info_info_type" FOREIGN KEY
		(info_type_id)
	REFERENCES info_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_info_idx 
	ADD CONSTRAINT "movie_info_idx_title" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_info_idx 
	ADD CONSTRAINT "movie_info_idx_info_type" FOREIGN KEY
		(info_type_id)
	REFERENCES info_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_companies 
	ADD CONSTRAINT "movie_companies_title" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_companies 
	ADD CONSTRAINT "movie_companies_company_name" FOREIGN KEY
		(company_id)
	REFERENCES company_name
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE movie_companies 
	ADD CONSTRAINT "movie_companies_company_type" FOREIGN KEY
		(company_type_id)
	REFERENCES company_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE complete_cast 
	ADD CONSTRAINT "complete_cast_title" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE cast_info 
	ADD CONSTRAINT "cast_info_title" FOREIGN KEY
		(movie_id)
	REFERENCES title
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE cast_info 
	ADD CONSTRAINT "cast_info_name" FOREIGN KEY
		(person_id)
	REFERENCES name
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE cast_info 
	ADD CONSTRAINT "cast_info_role_type1" FOREIGN KEY
		(person_role_id)
	REFERENCES role_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE cast_info 
	ADD CONSTRAINT "cast_info_role_type2" FOREIGN KEY
		(role_id)
	REFERENCES role_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE person_info 
	ADD CONSTRAINT "person_info_name" FOREIGN KEY
		(person_id)
	REFERENCES name
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE person_info 
	ADD CONSTRAINT "person_info_info_type" FOREIGN KEY
		(info_type_id)
	REFERENCES info_type
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE aka_name 
	ADD CONSTRAINT "aka_name_name" FOREIGN KEY
		(person_id)
	REFERENCES name
		(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

commit;

connect reset;